/**
 * Public API contract in OpenAPI `info.description`.
 * Same facts as /docs Start. English only (machine spec).
 * No ops hosts, node bind, disk, or Caddy internals.
 */
export const OPENAPI_INFO_DESCRIPTION = [
  "# Introduction",
  "Access ErgoScan data such as blocks, boxes, transactions, addresses, tokens, NFTs, Spectrum DEX, Rosen, oracles, storage rent and mempool.",
  "",
  "Use our free API to power wallets and applications. No signup. No key. Same host as the explorer: https://ergoscan.me",
  "",
  "A link to ErgoScan is welcome. It is not required.",
  "",
  "# API Specification",
  "This API is documented in **OpenAPI format** at https://ergoscan.me/openapi.json",
  "",
  "Human docs: https://ergoscan.me/docs",
  "",
  "`/api/v1/*` and `/v1/*` are the same router. GraphQL is **POST** only (`/v1/graphql`, `/api/v1/graphql`). GET GraphQL returns 405.",
  "",
  "Responses come from our Postgres index and mempool RAM. This is the ErgoScan explorer API, not a live proxy of another site.",
  "",
  "nanoERG and token raw amounts are decimal **strings**. Parse with BigInt. Official explorer uses int64 and overflows LP and emission.",
  "",
  "Heights, global indexes, and sizes are JSON numbers. Timestamps are milliseconds since the Unix epoch (UTC).",
  "",
  "User GET does not call the node. The only user write is `POST /mempool/transactions/submit` and GraphQL `submitTx`. Client errors are `rejected` or `submit_failed`.",
  "",
  "An address that fails the Ergo checksum returns HTTP 400 `{ error: \"bad_address\", reason: \"checksum\" }`. A valid address with no history returns an empty result.",
  "",
  "Existing fields stay. New fields and paths may appear. `GET /tokens` catalog shape is frozen.",
  "",
  "GraphQL reads the same index. Query depth ≤ 7. gix windows ≤ 10000 (4s timeout). `submitTx` shares the submit rate limit.",
  "",
  "# Cross-Origin Resource Sharing",
  "This API sends `Access-Control-Allow-Origin: *`. Wallets and dApps may call from the browser. Do not send cookies or credentials.",
  "",
  "# Authentication",
  "This API does not require authentication. There is no API key and no paid plan.",
  "",
  "# Pagination",
  "This API uses keyset (cursor) pagination. When another page exists the JSON includes `hasMore: true` and `nextCursor`. Repeat the request with `?cursor=` set to that value.",
  "",
  "Wallet list endpoints also accept `limit` (max 100) and `offset` (max 500) as a small skip on an address-filtered index, not a table OFFSET down the chain. Prefer `cursor`.",
  "",
  "# Rate Limit",
  "Reads: **120 requests per minute per IP**. The window is one minute.",
  "",
  "Submit (`POST /mempool/transactions/submit` and GraphQL `submitTx`): **10 per minute** and **2 in flight**, one shared bucket.",
  "",
  "Over the limit the API returns HTTP 429 `{ error: \"rate_limited\", retryAfterSec }`. Read responses also send `X-RateLimit-Limit` and `X-RateLimit-Remaining`.",
  "",
  "WebSocket `/v1/stream` and `/v1/media/` are not counted in the read bucket.",
].join("\n");
